sudo: required
language: rust

services:
  - docker
  
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --release

after_success:
  - docker build . -t mooseCast/tcp

